# Generated by Django 5.2.7 on 2025-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_content_image_content_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
