# Generated by Django 5.2.3 on 2025-11-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_content_duration_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='main.content'),
        ),
    ]
