# Generated by Django 5.2.3 on 2025-11-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='content_pdfs/'),
        ),
    ]
